-- MySQL dump 10.13  Distrib 5.7.30, for Linux (x86_64)
--
-- Host: localhost    Database: cdr
-- ------------------------------------------------------
-- Server version	5.7.30-0ubuntu0.16.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `cdr`
--

DROP TABLE IF EXISTS `cdr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cdr` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `callid` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Call ID, generated by PBX',
  `a_number` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Full number of the caller',
  `hidden_anumber` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 - true if caller has the hidden number feature enabled, must be passed to b-leg',
  `b_number` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'The called number',
  `channel` varchar(32) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Not used',
  `start` datetime NOT NULL COMMENT 'Time the call arrives',
  `charge` datetime DEFAULT NULL COMMENT 'Time the call is answered and charge starts',
  `stop` datetime DEFAULT NULL COMMENT 'Time the call ends',
  `seconds` smallint(5) unsigned DEFAULT '0' COMMENT 'Total seconds of charge',
  `seconds_total` smallint(5) unsigned DEFAULT '0' COMMENT 'Total seconds of call',
  `direction` enum('IN','OUT') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Direction of call',
  `original_callid` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'If a b-leg, this is callid of corresponding a-leg',
  `original_a_number` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'If a b-leg, this is a-number of a-leg',
  `original_b_number` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'If a b-leg, this is b-number of a-leg',
  `program` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Shows the call flow of the call',
  `clearcause` tinyint(3) unsigned DEFAULT '0' COMMENT 'Shows the reason/cause of call to end/disconnect',
  `serviceCategory` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The service category of this service',
  `sipcallid` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The call id of the sip server',
  `imported_in_main_cdr` tinyint(1) DEFAULT '0' COMMENT '1 - true if this record har been imported to main CDR system',
  `last_imported_in_main_cdr` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'Date and time this record was imported',
  PRIMARY KEY (`start`,`id`),
  KEY `callid_idx` (`callid`) USING BTREE,
  KEY `cdr_stats_idx` (`start`,`original_b_number`,`direction`),
  KEY `charge_idx` (`charge`),
  KEY `stop_idx` (`stop`),
  KEY `channel_idx` (`channel`),
  KEY `start_idx` (`start`) USING BTREE,
  KEY `a_number` (`a_number`),
  KEY `id` (`id`),
  KEY `program` (`program`)
) ENGINE=InnoDB AUTO_INCREMENT=272589 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
/*!50100 PARTITION BY KEY (`start`)
PARTITIONS 12 */;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `cdr_stat_trigger_INSERT` AFTER INSERT ON `cdr` FOR EACH ROW BEGIN

	IF new.clearcause > 0 THEN
	
		INSERT INTO `stats`.`cdr_stat_daily`
		(`number`,
		`original_number`,
		`timestamp`,
		`direction`,
		`count_charge`,
		`count_call`,
		`count_charge_sec`,
		`count_call_sec`)
		VALUES
		(NEW.b_number,
		NEW.`original_b_number`,
		CAST(NEW.`start` AS DATE),
		NEW.direction,
		IF(NEW.`charge` IS NULL,0,1),
		1,
		ABS(TIMESTAMPDIFF(SECOND,
		            COALESCE(NEW.`charge`, NEW.`stop`),
		            NEW.`stop`)),
		TIMESTAMPDIFF(SECOND,
		            NEW.`start`,
		            COALESCE(NEW.`stop`, NEW.`start`)))
		            ON DUPLICATE KEY UPDATE 
			`count_charge` = `count_charge` + VALUES(`count_charge`),
			`count_call` = `count_call` + VALUES(`count_call`),
			`count_charge_sec` = `count_charge_sec` + VALUES(`count_charge_sec`),
			`count_call_sec` = `count_call_sec` + VALUES(`count_call_sec`);
    
 		INSERT INTO `stats`.`cdr_stat_hh`
		(`number`,
		`original_number`,
		`timestamp`,
		`direction`,
		`count_charge`,
		`count_call`,
		`count_charge_sec`,
		`count_call_sec`)
		VALUES
		(NEW.b_number,
		NEW.`original_b_number`,
		FROM_UNIXTIME((FLOOR((UNIX_TIMESTAMP(NEW.`start`) / (60 * 30))) * (60 * 30))),
		NEW.direction,
		IF(NEW.`charge` IS NULL,0,1),
		1,
		ABS(TIMESTAMPDIFF(SECOND,
		            COALESCE(NEW.`charge`, NEW.`stop`),
		            NEW.`stop`)),
		TIMESTAMPDIFF(SECOND,
		            NEW.`start`,
		            COALESCE(NEW.`stop`, NEW.`start`)))
		            ON DUPLICATE KEY UPDATE 
			`count_charge` = `count_charge` + VALUES(`count_charge`),
			`count_call` = `count_call` + VALUES(`count_call`),
			`count_charge_sec` = `count_charge_sec` + VALUES(`count_charge_sec`),
			`count_call_sec` = `count_call_sec` + VALUES(`count_call_sec`);   
    
    END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `cdr_stat_trigger_UPDATE` AFTER UPDATE ON `cdr` FOR EACH ROW BEGIN

	IF new.clearcause > 0 THEN
	
		INSERT INTO `stats`.`cdr_stat_daily`
		(`number`,
		`original_number`,
		`timestamp`,
		`direction`,
		`count_charge`,
		`count_call`,
		`count_charge_sec`,
		`count_call_sec`)
		VALUES
		(NEW.b_number,
		NEW.`original_b_number`,
		CAST(NEW.`start` AS DATE),
		NEW.direction,
		IF(NEW.`charge` IS NULL,0,1),
		1,
		ABS(TIMESTAMPDIFF(SECOND,
		            COALESCE(NEW.`charge`, NEW.`stop`),
		            NEW.`stop`)),
		TIMESTAMPDIFF(SECOND,
		            NEW.`start`,
		            COALESCE(NEW.`stop`, NEW.`start`)))
		            ON DUPLICATE KEY UPDATE 
			`count_charge` = `count_charge` + VALUES(`count_charge`),
			`count_call` = `count_call` + VALUES(`count_call`),
			`count_charge_sec` = `count_charge_sec` + VALUES(`count_charge_sec`),
			`count_call_sec` = `count_call_sec` + VALUES(`count_call_sec`);
			
		INSERT INTO `stats`.`cdr_stat_hh`
		(`number`,
		`original_number`,
		`timestamp`,
		`direction`,
		`count_charge`,
		`count_call`,
		`count_charge_sec`,
		`count_call_sec`)
		VALUES
		(NEW.b_number,
		NEW.`original_b_number`,
		FROM_UNIXTIME((FLOOR((UNIX_TIMESTAMP(NEW.`start`) / (60 * 30))) * (60 * 30))),
		NEW.direction,
		IF(NEW.`charge` IS NULL,0,1),
		1,
		ABS(TIMESTAMPDIFF(SECOND,
		            COALESCE(NEW.`charge`, NEW.`stop`),
		            NEW.`stop`)),
		TIMESTAMPDIFF(SECOND,
		            NEW.`start`,
		            COALESCE(NEW.`stop`, NEW.`start`)))
		            ON DUPLICATE KEY UPDATE 
			`count_charge` = `count_charge` + VALUES(`count_charge`),
			`count_call` = `count_call` + VALUES(`count_call`),
			`count_charge_sec` = `count_charge_sec` + VALUES(`count_charge_sec`),
			`count_call_sec` = `count_call_sec` + VALUES(`count_call_sec`);
	END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;

--
-- Table structure for table `cdr_archive`
--

DROP TABLE IF EXISTS `cdr_archive`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cdr_archive` (
  `callid` varchar(50) DEFAULT NULL,
  `a_number` varchar(40) DEFAULT NULL,
  `hidden_anumber` tinyint(1) DEFAULT NULL,
  `b_number` varchar(30) DEFAULT NULL,
  `channel` varchar(32) DEFAULT NULL,
  `start` datetime DEFAULT NULL,
  `charge` datetime DEFAULT NULL,
  `stop` datetime DEFAULT NULL,
  `seconds` smallint(5) unsigned DEFAULT NULL,
  `direction` enum('IN','OUT') DEFAULT NULL,
  `original_callid` varchar(50) DEFAULT NULL,
  `original_a_number` varchar(40) DEFAULT NULL,
  `original_b_number` varchar(32) DEFAULT NULL,
  `program` text,
  `clearcause` smallint(5) unsigned DEFAULT NULL,
  `serviceCategory` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Temporary table structure for view `cdr_stat_daily_view`
--

DROP TABLE IF EXISTS `cdr_stat_daily_view`;
/*!50001 DROP VIEW IF EXISTS `cdr_stat_daily_view`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `cdr_stat_daily_view` AS SELECT 
 1 AS `number`,
 1 AS `original_number`,
 1 AS `timestamp`,
 1 AS `direction`,
 1 AS `count_charge`,
 1 AS `count_call`,
 1 AS `count_charge_sec`,
 1 AS `count_call_sec`*/;
SET character_set_client = @saved_cs_client;

--
-- Temporary table structure for view `cdr_stat_today_view`
--

DROP TABLE IF EXISTS `cdr_stat_today_view`;
/*!50001 DROP VIEW IF EXISTS `cdr_stat_today_view`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `cdr_stat_today_view` AS SELECT 
 1 AS `number`,
 1 AS `original_number`,
 1 AS `timestamp`,
 1 AS `direction`,
 1 AS `count_charge`,
 1 AS `count_call`,
 1 AS `count_charge_sec`,
 1 AS `count_call_sec`*/;
SET character_set_client = @saved_cs_client;

--
-- Temporary table structure for view `cdr_stat_yesterday_view`
--

DROP TABLE IF EXISTS `cdr_stat_yesterday_view`;
/*!50001 DROP VIEW IF EXISTS `cdr_stat_yesterday_view`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `cdr_stat_yesterday_view` AS SELECT 
 1 AS `number`,
 1 AS `original_number`,
 1 AS `timestamp`,
 1 AS `direction`,
 1 AS `count_charge`,
 1 AS `count_call`,
 1 AS `count_charge_sec`,
 1 AS `count_call_sec`*/;
SET character_set_client = @saved_cs_client;

--
-- Final view structure for view `cdr_stat_daily_view`
--

/*!50001 DROP VIEW IF EXISTS `cdr_stat_daily_view`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8mb4 */;
/*!50001 SET character_set_results     = utf8mb4 */;
/*!50001 SET collation_connection      = utf8mb4_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `cdr_stat_daily_view` AS select `cdr`.`b_number` AS `number`,`cdr`.`original_b_number` AS `original_number`,cast(`cdr`.`start` as date) AS `timestamp`,`cdr`.`direction` AS `direction`,count(`cdr`.`charge`) AS `count_charge`,count(`cdr`.`start`) AS `count_call`,sum(abs(timestampdiff(SECOND,coalesce(`cdr`.`charge`,`cdr`.`stop`),`cdr`.`stop`))) AS `count_charge_sec`,sum(timestampdiff(SECOND,`cdr`.`start`,coalesce(`cdr`.`stop`,`cdr`.`start`))) AS `count_call_sec` from `cdr` where ((`cdr`.`clearcause` <> 0) and (length(`cdr`.`b_number`) > 0)) group by `cdr`.`b_number`,`cdr`.`original_b_number`,cast(`cdr`.`start` as date),`cdr`.`direction` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;

--
-- Final view structure for view `cdr_stat_today_view`
--

/*!50001 DROP VIEW IF EXISTS `cdr_stat_today_view`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8mb4 */;
/*!50001 SET character_set_results     = utf8mb4 */;
/*!50001 SET collation_connection      = utf8mb4_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `cdr_stat_today_view` AS select `cdr`.`b_number` AS `number`,`cdr`.`original_b_number` AS `original_number`,cast(`cdr`.`start` as date) AS `timestamp`,`cdr`.`direction` AS `direction`,count(`cdr`.`charge`) AS `count_charge`,count(`cdr`.`start`) AS `count_call`,sum(abs(timestampdiff(SECOND,coalesce(`cdr`.`charge`,`cdr`.`stop`),`cdr`.`stop`))) AS `count_charge_sec`,sum(timestampdiff(SECOND,`cdr`.`start`,coalesce(`cdr`.`stop`,`cdr`.`start`))) AS `count_call_sec` from `cdr` where ((`cdr`.`clearcause` <> 0) and (length(`cdr`.`b_number`) > 0) and (`cdr`.`start` > curdate())) group by `cdr`.`b_number`,`cdr`.`original_b_number`,cast(`cdr`.`start` as date),`cdr`.`direction` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;

--
-- Final view structure for view `cdr_stat_yesterday_view`
--

/*!50001 DROP VIEW IF EXISTS `cdr_stat_yesterday_view`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8mb4 */;
/*!50001 SET character_set_results     = utf8mb4 */;
/*!50001 SET collation_connection      = utf8mb4_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`tsip`@`%` SQL SECURITY DEFINER */
/*!50001 VIEW `cdr_stat_yesterday_view` AS select `cdr`.`b_number` AS `number`,`cdr`.`original_b_number` AS `original_number`,cast(`cdr`.`start` as date) AS `timestamp`,`cdr`.`direction` AS `direction`,count(`cdr`.`charge`) AS `count_charge`,count(`cdr`.`start`) AS `count_call`,sum(abs(timestampdiff(SECOND,coalesce(`cdr`.`charge`,`cdr`.`stop`),`cdr`.`stop`))) AS `count_charge_sec`,sum(timestampdiff(SECOND,`cdr`.`start`,coalesce(`cdr`.`stop`,`cdr`.`start`))) AS `count_call_sec` from `cdr` where ((`cdr`.`clearcause` <> 0) and (length(`cdr`.`b_number`) > 0) and (`cdr`.`start` > (curdate() - 1)) and (`cdr`.`start` < curdate())) group by `cdr`.`b_number`,`cdr`.`original_b_number`,cast(`cdr`.`start` as date),`cdr`.`direction` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-05-12 11:40:13
